using ObjCRuntime;

namespace AccessibilityBindings;

public enum AXAttribute
{
    Role,
    Subrole,
    RoleDescription,
    Title,
    Description,
    Help,
    Parent,
    Children,
    SelectedChildren,
    VisibleChildren,
    Window,
    TopLevelUIElement,
    TitleUIElement,
    ServesAsTitleForUIElements,
    LinkedUIElements,
    SharedFocusElements,
    Enabled,
    Focused,
    Position,
    Size,
    Value,
    ValueDescription,
    MinValue,
    MaxValue,
    ValueIncrement,
    ValueWraps,
    AllowedValues,
    SelectedText,
    SelectedTextRange,
    SelectedTextRanges,
    VisibleCharacterRange,
    NumberOfCharacters,
    SharedTextUIElements,
    SharedCharacterRange,
    Main,
    Minimized,
    CloseButton,
    ZoomButton,
    MinimizeButton,
    ToolbarButton,
    Proxy,
    GrowArea,
    Modal,
    DefaultButton,
    CancelButton,
    MenuItemCmdChar,
    MenuItemCmdVirtualKey,
    MenuItemCmdGlyph,
    MenuItemCmdModifiers,
    MenuItemMarkChar,
    MenuItemPrimaryUIElement,
    MenuBar,
    Windows,
    Frontmost,
    Hidden,
    MainWindow,
    FocusedWindow,
    FocusedUIElement,
    ExtrasMenuBar,
    HourField,
    MinuteField,
    SecondField,
    AMPMField,
    DayField,
    MonthField,
    YearField,
    Rows,
    VisibleRows,
    SelectedRows,
    Columns,
    VisibleColumns,
    SelectedColumns,
    SortDirection,
    ColumnHeaderUIElements,
    Index,
    Disclosing,
    DisclosedRows,
    DisclosedByRow,
    MatteHole,
    MatteContentUIElement,
    MarkerUIElements,
    Units,
    UnitDescription,
    MarkerType,
    MarkerTypeDescription,
    HorizontalScrollBar,
    VerticalScrollBar,
    Orientation,
    Header,
    Edited,
    Tabs,
    OverflowButton,
    Filename,
    Expanded,
    Selected,
    Splitters,
    Contents,
    NextContents,
    PreviousContents,
    Document,
    Incrementor,
    DecrementButton,
    IncrementButton,
    ColumnTitle,
    URL,
    LabelUIElements,
    LabelValue,
    ShownMenuUIElement,
    IsApplicationRunning,
    FocusedApplication,
    ElementBusy,
    AlternateUIVisible,
    PlaceholderValue,
    InsertionPointLineNumber,
    FullScreenButton,
    DisclosureLevel,
    SearchButton,
    ClearButton,
    RowCount,
    ColumnCount,
    OrderedByRow,
    WarningValue,
    CriticalValue,
    SelectedCells,
    VisibleCells,
    RowHeaderUIElements,
    RowIndexRange,
    ColumnIndexRange,
    HorizontalUnits,
    VerticalUnits,
    HorizontalUnitDescription,
    VerticalUnitDescription,
    Handles,
    Text,
    VisibleText,
    IsEditable,
    //ColumnTitles, //has the same (duplicate) string representation as the ColumnTitle, so I don't know know how to handle the bidirectional mapping correctly
    Identifier,
    LineForIndexParameterized,
    RangeForLineParameterized,
    StringForRangeParameterized,
    RangeForPositionParameterized,
    RangeForIndexParameterized,
    BoundsForRangeParameterized,
    RTFForRangeParameterized,
    AttributedStringForRangeParameterized,
    StyleRangeForIndexParameterized,
    CellForColumnAndRowParameterized,
    LayoutPointForScreenPointParameterized,
    LayoutSizeForScreenSizeParameterized,
    ScreenPointForLayoutPointParameterized,
    ScreenSizeForLayoutSizeParameterized
}

public static class AXAttributeExtensions
{
    private static readonly IReadOnlyDictionary<AXAttribute, string> EnumToString;
    private static readonly IReadOnlyDictionary<string, AXAttribute> StringToEnum;
    
    static AXAttributeExtensions()
    {
        EnumToString = new Dictionary<AXAttribute, string>
        {
            //values grabbed from https://github.com/eiz/accessibility/blob/f6f68d8615d2223c3e64d0a43f470acd2f1d51ef/accessibility-sys/src/attribute_constants.rs
            //TODO: somehow try to extract the actual values from framework in runtime (dlopen + GetString or something like this)?
            [AXAttribute.Role] = "AXRole",
            [AXAttribute.Subrole] = "AXSubrole",
            [AXAttribute.RoleDescription] = "AXRoleDescription",
            [AXAttribute.Help] = "AXHelp",
            [AXAttribute.Title] = "AXTitle",
            [AXAttribute.Value] = "AXValue",
            [AXAttribute.ValueDescription] = "AXValueDescription",
            [AXAttribute.MinValue] = "AXMinValue",
            [AXAttribute.MaxValue] = "AXMaxValue",
            [AXAttribute.ValueIncrement] = "AXValueIncrement",
            [AXAttribute.AllowedValues] = "AXAllowedValues",
            [AXAttribute.PlaceholderValue] = "AXPlaceholderValue",
            [AXAttribute.Enabled] = "AXEnabled",
            [AXAttribute.ElementBusy] = "AXElementBusy",
            [AXAttribute.Focused] = "AXFocused",
            [AXAttribute.Parent] = "AXParent",
            [AXAttribute.Children] = "AXChildren",
            [AXAttribute.SelectedChildren] = "AXSelectedChildren",
            [AXAttribute.VisibleChildren] = "AXVisibleChildren",
            [AXAttribute.Window] = "AXWindow",
            [AXAttribute.TopLevelUIElement] = "AXTopLevelUIElement",
            [AXAttribute.Position] = "AXPosition",
            [AXAttribute.Size] = "AXSize",
            [AXAttribute.Orientation] = "AXOrientation",
            [AXAttribute.Description] = "AXDescription",
//[AXAttribute.Description] = "AXDescription"; // old name
            [AXAttribute.SelectedText] = "AXSelectedText",
            [AXAttribute.SelectedTextRange] = "AXSelectedTextRange",
            [AXAttribute.SelectedTextRanges] = "AXSelectedTextRanges",
            [AXAttribute.VisibleCharacterRange] = "AXVisibleCharacterRange",
            [AXAttribute.NumberOfCharacters] = "AXNumberOfCharacters",
            [AXAttribute.SharedTextUIElements] = "AXSharedTextUIElements",
            [AXAttribute.SharedCharacterRange] = "AXSharedCharacterRange",
            [AXAttribute.SharedFocusElements] = "AXSharedFocusElements",
            [AXAttribute.InsertionPointLineNumber] = "AXInsertionPointLineNumber",
            [AXAttribute.Main] = "AXMain",
            [AXAttribute.Minimized] = "AXMinimized",
            [AXAttribute.CloseButton] = "AXCloseButton",
            [AXAttribute.ZoomButton] = "AXZoomButton",
            [AXAttribute.MinimizeButton] = "AXMinimizeButton",
            [AXAttribute.ToolbarButton] = "AXToolbarButton",
            [AXAttribute.FullScreenButton] = "AXFullScreenButton",
            [AXAttribute.Proxy] = "AXProxy",
            [AXAttribute.GrowArea] = "AXGrowArea",
            [AXAttribute.Modal] = "AXModal",
            [AXAttribute.DefaultButton] = "AXDefaultButton",
            [AXAttribute.CancelButton] = "AXCancelButton",
            [AXAttribute.MenuItemCmdChar] = "AXMenuItemCmdChar",
            [AXAttribute.MenuItemCmdVirtualKey] = "AXMenuItemCmdVirtualKey",
            [AXAttribute.MenuItemCmdGlyph] = "AXMenuItemCmdGlyph",
            [AXAttribute.MenuItemCmdModifiers] = "AXMenuItemCmdModifiers",
            [AXAttribute.MenuItemMarkChar] = "AXMenuItemMarkChar",
            [AXAttribute.MenuItemPrimaryUIElement] = "AXMenuItemPrimaryUIElement",
//
// [AXAttribute.MenuItemModifierNone: u32 = 0;
// [AXAttribute.MenuItemModifierShift: u32 = 1 << 0;
// [AXAttribute.MenuItemModifierOption: u32 = 1 << 1;
// [AXAttribute.MenuItemModifierControl: u32 = 1 << 2;
// [AXAttribute.MenuItemModifierNoCommand: u32 = 1 << 3;

            [AXAttribute.MenuBar] = "AXMenuBar",
            [AXAttribute.Windows] = "AXWindows",
            [AXAttribute.Frontmost] = "AXFrontmost",
            [AXAttribute.Hidden] = "AXHidden",
            [AXAttribute.MainWindow] = "AXMainWindow",
            [AXAttribute.FocusedWindow] = "AXFocusedWindow",
            [AXAttribute.FocusedUIElement] = "AXFocusedUIElement",
            [AXAttribute.ExtrasMenuBar] = "AXExtrasMenuBar",
            [AXAttribute.Header] = "AXHeader",
            [AXAttribute.Edited] = "AXEdited",
            [AXAttribute.ValueWraps] = "AXValueWraps",
            [AXAttribute.Tabs] = "AXTabs",
            [AXAttribute.TitleUIElement] = "AXTitleUIElement",
            [AXAttribute.HorizontalScrollBar] = "AXHorizontalScrollBar",
            [AXAttribute.VerticalScrollBar] = "AXVerticalScrollBar",
            [AXAttribute.OverflowButton] = "AXOverflowButton",
            [AXAttribute.Filename] = "AXFilename",
            [AXAttribute.Expanded] = "AXExpanded",
            [AXAttribute.Selected] = "AXSelected",
            [AXAttribute.Splitters] = "AXSplitters",
            [AXAttribute.NextContents] = "AXNextContents",
            [AXAttribute.Document] = "AXDocument",
            [AXAttribute.DecrementButton] = "AXDecrementButton",
            [AXAttribute.IncrementButton] = "AXIncrementButton",
            [AXAttribute.PreviousContents] = "AXPreviousContents",
            [AXAttribute.Contents] = "AXContents",
            [AXAttribute.Incrementor] = "AXIncrementor",
            [AXAttribute.HourField] = "AXHourField",
            [AXAttribute.MinuteField] = "AXMinuteField",
            [AXAttribute.SecondField] = "AXSecondField",
            [AXAttribute.AMPMField] = "AXAMPMField",
            [AXAttribute.DayField] = "AXDayField",
            [AXAttribute.MonthField] = "AXMonthField",
            [AXAttribute.YearField] = "AXYearField",
            [AXAttribute.ColumnTitle] = "AXColumnTitles",
            [AXAttribute.URL] = "AXURL",
            [AXAttribute.LabelUIElements] = "AXLabelUIElements",
            [AXAttribute.LabelValue] = "AXLabelValue",
            [AXAttribute.ShownMenuUIElement] = "AXShownMenuUIElement",
            [AXAttribute.ServesAsTitleForUIElements] = "AXServesAsTitleForUIElements",
            [AXAttribute.LinkedUIElements] = "AXLinkedUIElements",
            [AXAttribute.Rows] = "AXRows",
            [AXAttribute.VisibleRows] = "AXVisibleRows",
            [AXAttribute.SelectedRows] = "AXSelectedRows",
            [AXAttribute.Columns] = "AXColumns",
            [AXAttribute.VisibleColumns] = "AXVisibleColumns",
            [AXAttribute.SelectedColumns] = "AXSelectedColumns",
            [AXAttribute.SortDirection] = "AXSortDirection",
            [AXAttribute.Index] = "AXIndex",
            [AXAttribute.Disclosing] = "AXDisclosing",
            [AXAttribute.DisclosedRows] = "AXDisclosedRows",
            [AXAttribute.DisclosedByRow] = "AXDisclosedByRow",
            [AXAttribute.DisclosureLevel] = "AXDisclosureLevel",
            [AXAttribute.MatteHole] = "AXMatteHole",
            [AXAttribute.MatteContentUIElement] = "AXMatteContentUIElement",
            [AXAttribute.MarkerUIElements] = "AXMarkerUIElements",
            [AXAttribute.Units] = "AXUnits",
            [AXAttribute.UnitDescription] = "AXUnitDescription",
            [AXAttribute.MarkerType] = "AXMarkerType",
            [AXAttribute.MarkerTypeDescription] = "AXMarkerTypeDescription",
            [AXAttribute.IsApplicationRunning] = "AXIsApplicationRunning",
            [AXAttribute.SearchButton] = "AXSearchButton",
            [AXAttribute.ClearButton] = "AXClearButton",
            [AXAttribute.FocusedApplication] = "AXFocusedApplication",
            [AXAttribute.RowCount] = "AXRowCount",
            [AXAttribute.ColumnCount] = "AXColumnCount",
            [AXAttribute.OrderedByRow] = "AXOrderedByRow",
            [AXAttribute.WarningValue] = "AXWarningValue",
            [AXAttribute.CriticalValue] = "AXCriticalValue",
            [AXAttribute.SelectedCells] = "AXSelectedCells",
            [AXAttribute.VisibleCells] = "AXVisibleCells",
            [AXAttribute.RowHeaderUIElements] = "AXRowHeaderUIElements",
            [AXAttribute.ColumnHeaderUIElements] = "AXColumnHeaderUIElements",
            [AXAttribute.RowIndexRange] = "AXRowIndexRange",
            [AXAttribute.ColumnIndexRange] = "AXColumnIndexRange",
            [AXAttribute.HorizontalUnits] = "AXHorizontalUnits",
            [AXAttribute.VerticalUnits] = "AXVerticalUnits",
            [AXAttribute.HorizontalUnitDescription] = "AXHorizontalUnitDescription",
            [AXAttribute.VerticalUnitDescription] = "AXVerticalUnitDescription",
            [AXAttribute.Handles] = "AXHandles",
            [AXAttribute.Text] = "AXText",
            [AXAttribute.VisibleText] = "AXVisibleText",
            [AXAttribute.IsEditable] = "AXIsEditable",
            //[AXAttribute.ColumnTitles] = "AXColumnTitles", //strange item - different key, but the value is the same as for the ColumnTitle
            [AXAttribute.Identifier] = "AXIdentifier",
            [AXAttribute.AlternateUIVisible] = "AXAlternateUIVisible",
            [AXAttribute.LineForIndexParameterized] = "AXLineForIndex",
            [AXAttribute.RangeForLineParameterized] = "AXRangeForLine",
            [AXAttribute.StringForRangeParameterized] = "AXStringForRange",
            [AXAttribute.RangeForPositionParameterized] = "AXRangeForPosition",
            [AXAttribute.RangeForIndexParameterized] = "AXRangeForIndex",
            [AXAttribute.BoundsForRangeParameterized] = "AXBoundsForRange",
            [AXAttribute.RTFForRangeParameterized] = "AXRTFForRange",
            [AXAttribute.AttributedStringForRangeParameterized] = "AXAttributedStringForRange",
            [AXAttribute.StyleRangeForIndexParameterized] = "AXStyleRangeForIndex",
            [AXAttribute.CellForColumnAndRowParameterized] = "AXCellForColumnAndRow",
            [AXAttribute.LayoutPointForScreenPointParameterized] = "AXLayoutPointForScreenPoint",
            [AXAttribute.LayoutSizeForScreenSizeParameterized] = "AXLayoutSizeForScreenSize",
            [AXAttribute.ScreenPointForLayoutPointParameterized] = "AXScreenPointForLayoutPoint",
            [AXAttribute.ScreenSizeForLayoutSizeParameterized] = "AXScreenSizeForLayoutSize",
        };

        System.Diagnostics.Debug.Assert(Enum.GetValues<AXAttribute>().All(x => EnumToString.ContainsKey(x)));
        StringToEnum = EnumToString.ToDictionary(x => x.Value, x => x.Key);
    }
    
    public static string GetConstant(this AXAttribute attribute) => EnumToString[attribute];

    public static AXAttribute GetValue(string attribute) => StringToEnum[attribute];
}